language: android
jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.0
    - android-25
    - extra-android-m2repository

# licenses:
#  - android-sdk-preview-license-.+
#  - android-sdk-license-.+
#  - google-gdk-license-.+
before_script:
  android update sdk --no-ui --filter build-tools-25.0.0,android-25,extra-android-m2repository

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
- ./gradlew assembleRelease

before_install:
# - rvm install 2.2.0 --disable-binary
# - rvm use ruby-2.2.0 --default
# - gem install fir-cli
- openssl aes-256-cbc -K $encrypted_33ee19960fe4_key -iv $encrypted_33ee19960fe4_iv
  -in xifan.jks.enc -out ./xifan.jks -d

after_deploy:
- fir p app/build/outputs/apk/app-release.apk -T $FIR_TOKEN -c "`git cat-file tag $TRAVIS_TAG`"
