language: android
sudo: false
jdk: oraclejdk8
android:
  components:
  - build-tools-23.0.2
  - android-22
  - extra-android-m2repository
  - extra-android-support
script:
# - ./gradlew assembleRelease
before_install:
- openssl aes-256-cbc -K $encrypted_33ee19960fe4_key -iv $encrypted_33ee19960fe4_iv
  -in xifan.jks.enc -out ./xifan.jks -d
- ls
