language: android
rvm:
  - 2.2
  - jruby
sudo: false
jdk: oraclejdk8

android:
  components:
  - build-tools-23.0.2
  - android-22
  - extra-android-m2repository
  - extra-android-support

script:
- ./gradlew assembleRelease

before_install:
# - rvm install 2.2.0 --disable-binary
# - rvm use ruby-2.2.0 --default
- gem install fir-cli
- openssl aes-256-cbc -K $encrypted_9832fa0e04b3_key -iv $encrypted_9832fa0e04b3_iv
  -in xifan.jks.enc -out ./xifan.jks -d

after_deploy:
- fir p app/build/outputs/apk/app-release.apk -T $FIR_TOKEN -c "`git cat-file tag $TRAVIS_TAG`"
